require_relative '../lib/woven'
require 'fiber'
require 'minitest/autorun'
require 'minitest/pride'
require 'minitest/spec'
require 'pry'
require 'webmock/minitest'

require_relative './channel_test'
#require_relative './future_test'
#require_relative './promise_test'
